# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.5.0
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo apt-get update && sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - run:
          name: Checking Dependencies
          command: |
            node --version
            npm --version

      - run: sudo npm install -g npm@5.7.1
      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run:
          name: Start
          command: npm run start
          background: true
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Stylelint
          command: npm run stylelint
      - run:
          name: Test
          command: npm test
    #   - run:
    #       name: Generate code coverage
    #       command: npm run test:ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: BundleSize
          command: npm run test:size
      - run:
          name: E2E Tests Cypress
          command: npm run cypress:run
      - store_artifacts:
          path: cypress/videos